FROM mhart/alpine-node:14.15

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

ENV NEXT_PUBLIC_API_HOST http://67.207.75.74/api
ENV NEXT_PUBLIC_WS_HOST ws://138.68.124.183
ENV NEXT_PUBLIC_FRONTEND_HOST http://67.207.76.234

RUN npm run build

CMD npm run start