export const TOOLBAR_BRUSH_WIDTH_LOW = 2
export const TOOLBAR_BRUSH_WIDTH_MIDDLE = 4
export const TOOLBAR_BRUSH_WIDTH_BIG = 6

export const TOOLBAR_BRUSH_COLOR_RED = "#C0392B"
export const TOOLBAR_BRUSH_COLOR_BLUE = "#0056C5"
export const TOOLBAR_BRUSH_COLOR_GREEN = "#83BE42"