export const TOOLBAR_BRUSH_WIDTH_LOW = 3
export const TOOLBAR_BRUSH_WIDTH_MIDDLE = 6
export const TOOLBAR_BRUSH_WIDTH_BIG = 10

export const TOOLBAR_BRUSH_COLOR_RED = "#C0392B"
export const TOOLBAR_BRUSH_COLOR_BLUE = "#0056C5"
export const TOOLBAR_BRUSH_COLOR_GREEN = "#5BAC31"

export const TOOLBAR_MODE_DRAW = 'TOOLBAR_MODE_DRAW'
export const TOOLBAR_MODE_ERASE = 'TOOLBAR_MODE_ERASE'

export const TOOLBAR_ERASER_WIDTH_LOW = 10
export const TOOLBAR_ERASER_WIDTH_MIDDLE = 20
export const TOOLBAR_ERASER_WIDTH_BIG = 35
